/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iUniSwapSol from "./IUniSwap.sol";
export type { iUniSwapSol };
export type { Stake } from "./Stake";
export type { Token } from "./Token";
